spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://local.fudges.cn:13307/lifestyle_prod?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 601202
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

  data:
    redis:
      port: 6699
      host: local.fudges.cn
      password: fudges
      timeout: 1000
      database: 0
      redisson:
        connect-timeout: 1000
        connection-pool-size: 80

project:
  domain: http://local.fudges.cn:${server.port}
  file:
    pre-path: /uploads
    upload-dir: ${user.dir}/uploads
    auth-exclude:
      - ${project.file.pre-path}/userAvatar/**